title: migs music
description: Local music player for Android, with a Mac sidekick that syncs Apple Music playlists over USB.
theme: jekyll-theme-cayman
url: https://michaelhball.github.io
baseurl: /migs-music
